// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY
// If you want to change the content of this file, you need to edit
// file '/dictionaries/en.po' and run '.po' extractor
export const base = {
  'base.buttons.createRequest': 'Create a request',

  'base.buttons.save': 'Save',

  'components.organisms.Page.title': 'Main',

  'components.routes.pages.Error404.body':
    'This is not the page you’re looking for :(',
  'components.routes.pages.Error404.title': '404 Not found',
  'components.routes.pages.Main.title': 'Main',
  'components.routes.pages.User.notFound': 'User not found',
  'components.routes.pages.User.title': 'Main Page',

  'components.templates.WithHeader.goBack': 'Go back',
};
